find_program(TEXLOGFILTER_EXECUTABLE
	 texlogfilter
	 PATHS ${TEXLOGFILTER_ROOT}
				 ${TEXLOGFILTER_DIR}
)

if(TEXLOGFILTER_EXECUTABLE)
	execute_process(COMMAND ${TEXLOGFILTER_EXECUTABLE} --version
		OUTPUT_VARIABLE TEXLOGFILTER_VERSION_STRING
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TexLogFilter
		FOUND_VAR TEXLOGFILTER_FOUND
		REQUIRED_VARS TEXLOGFILTER_EXECUTABLE
		VERSION_VAR TEXLOGFILTER_VERSION_STRING
)
